time_bank/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: "initial_page#index"

  resources :users, only: %i[show]
  get "profile", to: "users#profile"

  resources :transactions, only: %i[index new create]
  delete "transactions/destroy", to: "transactions#destroy"
  put "transactions/deny", to: "transactions#deny"
  put "transactions/accept", to: "transactions#accept"

  resources :reports, only: %i[index]
  post "reports/search", to: "reports#search"
  post "reports/csv", to: "reports#generate_csv"

  resources :projects, only: %i[index new create edit update]
  get "projects/entity", to: "projects#entity"

  get "admin/dashboard", to: "admin#dashboard"
  get "admin/users", to: "admin#users"
  get "admin/entities", to: "admin#entities"
  get "admin/information", to: "admin#information"
  get "admin/bank_hours", to: "admin#bank_hours"

  put "admin/update_entity", to: "admin#update_entity"
  put "admin/update_user", to: "admin#update_user"

  post "admin/update_user", to: "admin#update_user"

  resources :talents
  resources :messages, only: %i[index new create]
  resources :information
end

time_bank/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :talents
  has_many :projects
  has_many :provider_transactions, class_name: "Transaction", foreign_key: "provider_id"
  has_many :receiver_transactions, class_name: "Transaction", foreign_key: "receiver_id"
  has_many :sender_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :receiver_messages, class_name: "Message", foreign_key: "receiver_id"

  enum status: [:pendente, :ativo, :inativo]

  validates :name, presence: true

  scope :entities, -> { where(entity: true) }
  scope :not_entities, -> { where(entity: false) }
  scope :has_talent, -> { includes(:talents).where.not(talents: { id: nil }) }

  def entity?
    self.entity == true
  end

  def active?
    self.status == "ativo"
  end
end

time_bank/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @hours = @user.hours
  end

  def profile
    @user = User.find(params[:profile_id])
    @transaction = Transaction.new
    @message = Message.new
  end
end

time_bank/app/views/users/_user_format.html.erb
<div class="container mt-3">
  <div class="row align-items-center">
    <div class="col-md-6 col-lg-4">
      <%= image_tag "th-3052408390.jpeg", style: "border-radius: 50%;", size: "300x300" %>
    </div>

    <div class="container col-md-6 col-lg-8 p-3 mb-2">
      <div class="card shadow">
        <div class="card-header d-flex" style="background-color: #50BF97; color: #023E73;">
          <div class="mr-auto p-2">
            <h2 style="font-weight: bold;"><%=@user.name%></h2>
          </div>
          <% if @user.id == current_user.id %>
            <div class="p-2"> 
              <%= link_to "Editar Perfil", edit_user_registration_path, class: "btn btn-dark" %>
            </div>
          <% end %>
        </div>
        <div class="container p-4" style="background-color: #EDEBEB;">
          <div class="card shadow" style="background-color: #FFFFFF;">
            <div class="card-body overflow-auto" style="max-height: 300px;">
              <%= @user.description %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card shadow mt-3">
    <% if @user.entity? %>
      <div class="card-header d-flex">
        <div class="mr-auto p-2">
          <h4 style="color: #023E73; font-weight: bold;">Projetos</h4> 
        </div>
        <% if @user.id == current_user.id %>
          <div class="p-2">
            <%= link_to "Criar Projeto", new_project_path , class: "btn btn-dark" %>
          </div>
        <% end %>
      </div>
    
      <div class="card-body d-flex flex-column" style="background-color: #FFFFFF;">
        <div id="accordion">  
          <% unless @user.projects.nil? %>
            <% @user.projects.each do |project| %>
              <div class="card shadow">
                <div class="card-header d-flex" id="heading-<%= project.id %>">
                  <h5 class="mb-0 mr-auto p-2">
                    <button class="btn btn-default text-left" data-toggle="collapse" data-target="#collapse-<%= project.id %>" aria-expanded="true" aria-controls="collapse-<%= project.id %>">
                      <%= project.name %>
                    </button>
                  </h5>

                  <% if @user.id == current_user.id %>
                    <div class="p-2">
                        <%= link_to "Editar", edit_project_path(project) , class: "btn btn-dark" %>
                    </div>
                  <% else %>
                    <div class="p-2">
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#schedule" data-talent="<%= project.name %>">
                        Solicitar Participação
                      </button>
                    </div>
                  <% end %>                 
                </div>

                <div id="collapse-<%= project.id %>" class="collapse" aria-labelledby="heading-<%= project.id %>" data-parent="#accordion">
                  <div class="card-body overflow-auto d-flex flex-column" style="max-height: 200px;">
                    <%= project.description %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

    <% else %>
      <div class="card-header d-flex">
          <div class="mr-auto p-2">
            <h4 style="color: #023E73; font-weight: bold;">Talentos</h4> 
          </div>
          <% if @user.id == current_user.id %>
            <div class="p-2">
              <%= link_to "Adicionar Talento", new_talent_path, class: "btn btn-dark" %>
            </div>
          <% end %>
      </div>
  
      <div class="card-body d-flex flex-column" style="background-color: #FFFFFF;">
        <div id="accordion">  
          <% unless @user.talents.nil? %>
            <% @user.talents.each do |talent| %>
              <div class="card shadow">
                <div class="card-header d-flex" id="heading-<%= talent.id %>">
                  <h5 class="mb-0 mr-auto p-2 col-md-10">
                    <button class="btn btn-default text-left" data-toggle="collapse" data-target="#collapse-<%= talent.id %>" aria-expanded="true" aria-controls="collapse-<%= talent.id %>">
                      <%= talent.name %>
                    </button>
                  </h5>

                  <% if @user.id == current_user.id %>
                    <div class="ml-auto p-2">
                      <%= link_to "Editar", edit_talent_path(talent) , class: "btn btn-dark" %>
                    </div>
                  <% elsif !current_user.entity? %>
                    <div class="p-2">
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#schedule" data-talent="<%= talent.name %>">
                        Solicitar Horas
                      </button>
                    </div>
                  <% end %>
                </div>

                <div id="collapse-<%= talent.id %>" class="collapse" aria-labelledby="heading-<%= talent.id %>" data-parent="#accordion">
                  <div class="card-body overflow-auto d-flex flex-column" style="max-height: 200px;">
                    <%= talent.description %>
                  </div>              
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <% if @user.id != current_user.id %>
    <div class="card-body">
      <h3>Deixe uma mensagem</h3>

      <%= form_for @message do |f| %>
        <div class="field col-md-12 form-group">
          <%= f.text_area :message, class: "form-control", :rows => 3, :required => true%>
        </div>

        <%= f.hidden_field :receiver_id, value: @user.id %>

        <div class="actions form-group form-row">
          <div class="col-sm-6">
            <%= f.submit "Enviar", class: "btn btn-success form-control" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<% if @user.id != current_user.id %>
  <!-- MODAL -->
  <div class="modal fade" id="schedule" tabindex="-1" role="dialog" aria-labelledby="scheduleLabel" aria-hidden="true">

  <script>
    $('#schedule').on('show.bs.modal', function (event) {
      console.log("executed")
      var button = $(event.relatedTarget) // Button that triggered the modal
      var recipient = button.data('talent') // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      console.log(recipient)
      var modal = $(this)
      modal.find('#transaction_hours').val(0)
      modal.find('#transaction_talent').val(recipient)
    })
  </script>

    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="scheduleLabel">Solicitar Horas</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        
        <%= form_for @transaction do |f| %>
          <div class="modal-body">
              <div class="form-group">
                <%= f.label :hours, "Horas" %>
                <%= f.text_field :hours, class:"form-control", :required => true, type: "number", placeholder: "0" %>

                <%= f.hidden_field :talent, value: "" %>
                <%= f.hidden_field :receiver_id, value: @user.id %>
                <small id="horasHelp" class="form-text text-muted">As horas solicitadas vão ser debitadas do seu saldo.</small>
              </div>
              <!--<input type="hidden" name="talent-id" id="talent-id" value=""/>-->
          </div>

          <div class="modal-footer">
            <%= f.submit "Solicitar", class: "btn btn-primary" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

time_bank/app/views/users/profile.html.erb
<%= render 'user_format'%>

time_bank/app/views/users/show.html.erb
<%= render 'user_format'%>