time_bank/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: "initial_page#index"

  resources :users, only: %i[show]
  get "profile", to: "users#profile"

  resources :transactions, only: %i[index new create]
  delete "transactions/destroy", to: "transactions#destroy"
  put "transactions/deny", to: "transactions#deny"
  put "transactions/accept", to: "transactions#accept"

  resources :reports, only: %i[index]
  post "reports/search", to: "reports#search"
  post "reports/csv", to: "reports#generate_csv"

  resources :projects, only: %i[index new create edit update]
  get "projects/entity", to: "projects#entity"

  get "admin/dashboard", to: "admin#dashboard"
  get "admin/users", to: "admin#users"
  get "admin/entities", to: "admin#entities"
  get "admin/information", to: "admin#information"
  get "admin/bank_hours", to: "admin#bank_hours"

  put "admin/update_entity", to: "admin#update_entity"
  put "admin/update_user", to: "admin#update_user"

  post "admin/update_user", to: "admin#update_user"

  resources :talents
  resources :messages, only: %i[index new create]
  resources :information
end

time_bank/app/views/admin/bank_hours.html.erb
<div class="card shadow m-3">
  <div class="card-header">
    <h2>Doações</h2>
  </div>

  <%= render 'transactions/table'%>
</div>

time_bank/app/views/admin/dashboard.html.erb
<div class="card shadow m-3">
  <div class="card-header">
    <h2>Dashboard</h2>
  </div>
  <div class="card-body">
    <nav class="mt-3">
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="usuarios-tab" data-toggle="tab" href="#usuarios" role="tab" aria-controls="usuarios" aria-selected="true">Usuários</a>
        <a class="nav-item nav-link" id="entities-tab" data-toggle="tab" href="#entities" role="tab" aria-controls="entities" aria-selected="false">Entidades</a>
        <a class="nav-item nav-link" id="noticias-tab" data-toggle="tab" href="#noticias" role="tab" aria-controls="noticias" aria-selected="false">Noticias</a>
      </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="usuarios" role="tabpanel" aria-labelledby="usuarios-tab">
        <% unless @users.nil? %>
          <table class="table table-striped mt-3">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Horas</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
              <td><%= user.name %></td>
              <td><%= user.hours %></td>
              <td><%= user.status %></td>
              <td>
                <% if user.status == "pendente" || user.status == "inativo" %>
                  <%= button_to 'Ativar', admin_update_user_path(user), params: { status: "ativo" }, method: :put, class: "btn btn-primary" %>
                <% elsif user.status == "ativo" %>
                  <%= button_to 'Desativar', admin_update_user_path(user), params: { status: "inativo" }, method: :put, class: "btn btn-danger" %>
                <% end %>
              </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% end %>
      </div>

      <div class="tab-pane fade" id="entities" role="tabpanel" aria-labelledby="entities-tab">
  
      <% unless @entities.nil? %>
        <table class="table table-striped mt-3">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Nome</th>
              <th scope="col">Horas</th>
              <th scope="col">Status</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @entities.each do |entity| %>
              <tr>
              <td><%= entity.name %></td>
              <td><%= entity.hours %></td>
              <td><%= entity.status %></td>
              <td>
                <% if entity.status == "pendente" || entity.status == "inativo" %>
                  <%= button_to "Ativar", admin_update_entity_path(entity), params: { status: "ativo" }, method: :put, class: "btn btn-primary" %>
                <% elsif entity.status == "ativo" %>
                  <%= button_to "Desativar", admin_update_entity_path(entity), params: { status: "inativo" }, method: :put, class: "btn btn-danger" %>
                <% end %>
              </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>

      <div class="tab-pane fade" id="noticias" role="tabpanel" aria-labelledby="noticias-tab">
        <div class="d-flex flex-column m-3">
          <div class="ml-auto">
            <%= link_to 'Adicionar notícia', new_information_path, class: "btn btn-primary" %>
          </div>
        </div>

        <% unless @information.nil? %>
          <table class="table table-striped mt-3">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Título</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <% @information.each do |information| %>
              <tr>
                <td><%= information.title %></td>
                <td><%= link_to 'Editar', edit_information_path(information), class: "btn btn-dark" %></td>
                <td><%= button_to 'Remover', information_path(information), method: :delete, class: "btn btn-danger" %></td>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>
  </div>

  <div class="p-2">
    <%= link_to "Horas do Banco", admin_bank_hours_path , class: "btn btn-dark" %>
  </div>
</div>