time_bank/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: "initial_page#index"

  resources :users, only: %i[show]
  get "profile", to: "users#profile"

  resources :transactions, only: %i[index new create]
  delete "transactions/destroy", to: "transactions#destroy"
  put "transactions/deny", to: "transactions#deny"
  put "transactions/accept", to: "transactions#accept"

  resources :reports, only: %i[index]
  post "reports/search", to: "reports#search"
  post "reports/csv", to: "reports#generate_csv"

  resources :projects, only: %i[index new create edit update]
  get "projects/entity", to: "projects#entity"

  get "admin/dashboard", to: "admin#dashboard"
  get "admin/users", to: "admin#users"
  get "admin/entities", to: "admin#entities"
  get "admin/information", to: "admin#information"
  get "admin/bank_hours", to: "admin#bank_hours"

  put "admin/update_entity", to: "admin#update_entity"
  put "admin/update_user", to: "admin#update_user"

  post "admin/update_user", to: "admin#update_user"

  resources :talents
  resources :messages, only: %i[index new create]
  resources :information
end

time_bank/app/models/talent.rb
# frozen_string_literal: true

class Talent < ApplicationRecord
  belongs_to :user

  enum category: [:ensino, :cuidado, :vida_domestica, :atividades_manuais]

  validates :name, :category, presence: true
end

time_bank/app/controllers/talents_controller.rb
# frozen_string_literal: true

class TalentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_talent, only: [:edit, :update, :destroy]

  def index
    @users = User.has_talent
  end

  def new
    @talent = Talent.new
  end

  def create
    @talent = Talent.new(talent_params)
    @talent.user = current_user

    if @talent.save
      flash[:notice] = "Cadastrado com sucesso."
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Não foi possível cadastrar talento, tente novamente."
      render :new
    end
  end

  def edit
  end

  def update
    if @talent.update(talent_params)
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Não foi possível atualizar talento, tente novamente."
      render :edit
    end
  end

  def destroy
    if @talent.destroy
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Não foi possível remover talento, tente novamente."
      render :edit
    end
  end

  private
    def set_talent
      @talent = Talent.find(params[:id])
    end

    def talent_params
      params.require(:talent).permit(:name, :description, :category)
    end
end

time_bank/app/views/talents/_form.html.erb
<div class="card-body">
  <%= form_for @talent do |f| %>
    <div class="field col-md-12 form-group">
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name, class:"form-control", :required => true%>
    </div>

    <div class="field col-md-12 form-group">
      <%= f.label :description, "Descrição" %>
      <%= f.text_area :description, class: "form-control", :rows => 3, :required => true%>
    </div>

    <div class="field col-md-12 form-group">
      <%= f.label :category, "Categoria" %>
      <%= f.select :category, options_for_select(Talent.categories.keys.to_a), {}, class: 'form-control', :required => true %>
    </div>

    <div class="actions form-group form-row">
      <div class="col-sm-6">
        <%= link_to 'Voltar', user_path(current_user), class: "btn btn-primary form-control" %>
      </div>
      <div class="col-sm-6">
        <%= f.submit "Salvar", class: "btn btn-success form-control" %>
      </div>
    </div>
  <% end %>
</div>

time_bank/app/views/talents/edit.html.erb
<div class="container" style="padding-top: 20px">
  <div class="card shadow">
    <div class="card-header">
        <h2>Editar talento</h2>
    </div>
    
    <%= render 'form'%>
  </div>

  <div class="card-body overflow-auto d-flex flex-column" style="max-height: 200px;">
    <div class="ml-auto p-2">
      <%= button_to 'Remover', talent_path(@talent), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>   
</div>

time_bank/app/views/talents/index.html.erb
<div class="row m-3">
  <% unless @users.nil? %>
    <% @users.each do |user| %>
      <div class="col-sm-6">
        <div class="card shadow mt-3" style="height: 18rem;">    
          <div class="card-header">
            <h3 class="mb-0"><%= link_to user.name, profile_path(profile_id: user.id), class:"link-secondary"%></h3>
          </div>
          
          <div class="card-body row overflow-auto">
              <% user.talents.each do |talent| %>
                
                <div class="col-md-12 p-1 mb-2 bg-info text-white rounded">
                  <%= talent.name %>
                </div>

              <% end %>
          </div>
          
          <div class="card-footer">
            <div>
              <% user.talents.select(:category).map(&:category).uniq.each do |category| %>
                <span class="badge badge-pill badge-secondary"><%= category %></span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

time_bank/app/views/talents/new.html.erb
<div class="container" style="padding-top: 20px">
  <div class="card shadow">
    <div class="card-header">
        <h2>Novo talento</h2>
    </div>
    
    <%= render 'form'%>
  </div>
</div>