time_bank/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: "initial_page#index"

  resources :users, only: %i[show]
  get "profile", to: "users#profile"

  resources :transactions, only: %i[index new create]
  delete "transactions/destroy", to: "transactions#destroy"
  put "transactions/deny", to: "transactions#deny"
  put "transactions/accept", to: "transactions#accept"

  resources :reports, only: %i[index]
  post "reports/search", to: "reports#search"
  post "reports/csv", to: "reports#generate_csv"

  resources :projects, only: %i[index new create edit update]
  get "projects/entity", to: "projects#entity"

  get "admin/dashboard", to: "admin#dashboard"
  get "admin/users", to: "admin#users"
  get "admin/entities", to: "admin#entities"
  get "admin/information", to: "admin#information"
  get "admin/bank_hours", to: "admin#bank_hours"

  put "admin/update_entity", to: "admin#update_entity"
  put "admin/update_user", to: "admin#update_user"

  post "admin/update_user", to: "admin#update_user"

  resources :talents
  resources :messages, only: %i[index new create]
  resources :information
end

time_bank/app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: [:deny, :accept, :destroy]

  def index
    @my_transactions = Transaction.where(provider: current_user)
    @request_transactions = Transaction.where(receiver: current_user)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    return hour_error if transaction_params[:hours].to_i <= 0

    receiver = User.find(transaction_params[:receiver_id])

    transaction = Transaction.new(
      talent: transaction_params[:talent],
      hours: transaction_params[:hours],
    )
    transaction.receiver = receiver
    transaction.provider = current_user

    if transaction.save
      redirect_to profile_path(profile_id: receiver.id)
    else
      flash[:alert] = "Não foi possível requisitar talento, tente novamente."
      redirect_to profile_path(profile_id: receiver.id)
    end
  end

  def deny
    if @transaction.update(status: :recusada)
      redirect_to transactions_path
    else
      flash[:alert] = "Não foi possível atualizar transação, tente novamente."
      redirect_to transactions_path
    end
  end

  def accept
    result = ExecuteTransaction.new(@transaction).call

    if result.success?
      redirect_to transactions_path
    else
      flash[:alert] = result.failure
      redirect_to transactions_path
    end
  end

  def destroy
    @transaction.destroy
    redirect_to transactions_path
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:talent, :hours, :receiver_id)
    end

    def hour_error
      flash[:alert] = "A quantidade mínima para requisitar um talento é uma hora."
      redirect_to profile_path(profile_id: transaction_params[:receiver_id])
    end
end

time_bank/app/views/transactions/_table.html.erb
<div class="card-body">
  <nav class="mt-3">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="recebidas-tab" data-toggle="tab" href="#recebidas" role="tab" aria-controls="recebidas" aria-selected="true">Recebidas</a>
      <% unless current_user.entity? %>
        <a class="nav-item nav-link" id="enviadas-tab" data-toggle="tab" href="#enviadas" role="tab" aria-controls="enviadas" aria-selected="false">Enviadas</a>
      <% end %>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade" id="enviadas" role="tabpanel" aria-labelledby="enviadas-tab">

      <% unless @my_transactions.empty? || current_user.entity? %>
        <table class="table table-striped">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Receptor</th>
              <th scope="col">Talento/Projeto</th>
              <th scope="col">Horas</th>
              <th scope="col">Status</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @my_transactions.each do |transaction| %>
              <tr>
                <td><%= transaction.receiver.name %></td>
                <td><%= transaction.talent %></td>
                <td><%= transaction.hours %></td>
                <td><%= transaction.status %></td>
                <td>
                <% if transaction.status == "pendente" %>
                  <%= button_to 'Cancelar', transactions_destroy_path, params: { id: transaction.id }, method: :delete, class: "btn btn-danger" %>
                <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
            <% else %>
                <p class="m-2"> Nenhuma requisição. </p>
          <% end %>
    </div>

    <div class="tab-pane fade show active" id="recebidas" role="tabpanel" aria-labelledby="recebidas-tab">
      
    <% unless @request_transactions.empty? %>
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Fornecedor</th>
            <th scope="col">Talento/Projeto</th>
            <th scope="col">Horas</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            <% @request_transactions.each do |transaction| %>
              <tr>
                <td><%= transaction.provider.name %></td>
                <td><%= transaction.talent %></td>
                <td><%= transaction.hours %></td>
                <td><%= transaction.status %></td>
                <td class="row">
                <% if transaction.status == "pendente" %>
                  <div class="col-md-6">
                  <%= button_to "", transactions_accept_path(transaction), params: { id: transaction.id }, method: :put, class: "btn btn-sm btn-success bi bi-check-lg" %>
                  </div>
                  <div class="col-md-6">
                  <%= button_to "", transactions_deny_path(transaction), params: { id: transaction.id }, method: :put, class: "btn btn-sm btn-danger bi bi-x-lg" %>
                  </div>
                <% end %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
      <% else %>
          <p class="m-2"> Nenhuma requisição. </p>
    <% end %>
  </div>
</div>

time_bank/app/views/transactions/index.html.erb
<div class="card shadow m-3">
  <div class="card-header">
    <h2>Requisições</h2>
  </div>

  <%= render 'table'%>
</div>